FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1-mesa-glx libglib2.0-0 ffmpeg libsm6 libxext6 \
    && rm -rf /var/lib/apt/lists/*

COPY app_requirements.txt .
RUN pip install --no-cache-dir -r app_requirements.txt

COPY images/ /app/images/
COPY app.py /app/

EXPOSE 5000

CMD ["python3", "app.py"]
